//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerWeb.SMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altiria.net/api/soap", ConfigurationName="SMS.SmsGatewayPort")]
    public interface SmsGatewayPort {
        
        // CODEGEN: Generating message contract since the operation sendSms is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PlannerWeb.SMS.sendSmsResponse sendSms(PlannerWeb.SMS.sendSmsRequest request);
        
        // CODEGEN: Generating message contract since the operation sendWapPush is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sendWapPush", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PlannerWeb.SMS.sendWapPushResponse sendWapPush(PlannerWeb.SMS.sendWapPushRequest request);
        
        // CODEGEN: Generating message contract since the operation getCredit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PlannerWeb.SMS.getCreditResponse getCredit(PlannerWeb.SMS.getCreditRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.altiria.net/api/soap")]
    public partial class TextMessageRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Credentials credentialsField;
        
        private string[] destinationField;
        
        private TextMessage messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Credentials credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
                this.RaisePropertyChanged("credentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("destination", Order=1)]
        public string[] destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TextMessage message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.altiria.net/api/soap")]
    public partial class Credentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string domainIdField;
        
        private string loginField;
        
        private string passwdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string domainId {
            get {
                return this.domainIdField;
            }
            set {
                this.domainIdField = value;
                this.RaisePropertyChanged("domainId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string passwd {
            get {
                return this.passwdField;
            }
            set {
                this.passwdField = value;
                this.RaisePropertyChanged("passwd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.altiria.net/api/soap")]
    public partial class WapPushDestination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string destinationField;
        
        private string statusField;
        
        private string idAckField;
        
        private string keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string idAck {
            get {
                return this.idAckField;
            }
            set {
                this.idAckField = value;
                this.RaisePropertyChanged("idAck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.altiria.net/api/soap")]
    public partial class WapPushMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgField;
        
        private string senderIdField;
        
        private string urlField;
        
        private bool ackField;
        
        private bool ackFieldSpecified;
        
        private string idAckField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string senderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("senderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
                this.RaisePropertyChanged("ack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ackSpecified {
            get {
                return this.ackFieldSpecified;
            }
            set {
                this.ackFieldSpecified = value;
                this.RaisePropertyChanged("ackSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string idAck {
            get {
                return this.idAckField;
            }
            set {
                this.idAckField = value;
                this.RaisePropertyChanged("idAck");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.altiria.net/api/soap")]
    public partial class TextDestination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string destinationField;
        
        private string statusField;
        
        private string idAckField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string idAck {
            get {
                return this.idAckField;
            }
            set {
                this.idAckField = value;
                this.RaisePropertyChanged("idAck");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.altiria.net/api/soap")]
    public partial class TextMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgField;
        
        private string senderIdField;
        
        private bool ackField;
        
        private bool ackFieldSpecified;
        
        private string idAckField;
        
        private string dPortField;
        
        private string sPortField;
        
        private string encodingField;
        
        private bool concatField;
        
        private bool concatFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string senderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("senderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
                this.RaisePropertyChanged("ack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ackSpecified {
            get {
                return this.ackFieldSpecified;
            }
            set {
                this.ackFieldSpecified = value;
                this.RaisePropertyChanged("ackSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string idAck {
            get {
                return this.idAckField;
            }
            set {
                this.idAckField = value;
                this.RaisePropertyChanged("idAck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=4)]
        public string dPort {
            get {
                return this.dPortField;
            }
            set {
                this.dPortField = value;
                this.RaisePropertyChanged("dPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=5)]
        public string sPort {
            get {
                return this.sPortField;
            }
            set {
                this.sPortField = value;
                this.RaisePropertyChanged("sPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool concat {
            get {
                return this.concatField;
            }
            set {
                this.concatField = value;
                this.RaisePropertyChanged("concat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool concatSpecified {
            get {
                return this.concatFieldSpecified;
            }
            set {
                this.concatFieldSpecified = value;
                this.RaisePropertyChanged("concatSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.altiria.net/api/soap")]
    public partial class TextMessageResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private TextDestination[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", Order=1)]
        public TextDestination[] details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altiria.net/api/soap", Order=0)]
        public PlannerWeb.SMS.TextMessageRequest TextMessageRequest;
        
        public sendSmsRequest() {
        }
        
        public sendSmsRequest(PlannerWeb.SMS.TextMessageRequest TextMessageRequest) {
            this.TextMessageRequest = TextMessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altiria.net/api/soap", Order=0)]
        public PlannerWeb.SMS.TextMessageResponse TextMessageResponse;
        
        public sendSmsResponse() {
        }
        
        public sendSmsResponse(PlannerWeb.SMS.TextMessageResponse TextMessageResponse) {
            this.TextMessageResponse = TextMessageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.altiria.net/api/soap")]
    public partial class WapPushMessageRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Credentials credentialsField;
        
        private string[] destinationField;
        
        private WapPushMessage messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Credentials credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
                this.RaisePropertyChanged("credentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("destination", Order=1)]
        public string[] destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public WapPushMessage message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.altiria.net/api/soap")]
    public partial class WapPushMessageResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private WapPushDestination[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", Order=1)]
        public WapPushDestination[] details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendWapPushRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altiria.net/api/soap", Order=0)]
        public PlannerWeb.SMS.WapPushMessageRequest WapPushMessageRequest;
        
        public sendWapPushRequest() {
        }
        
        public sendWapPushRequest(PlannerWeb.SMS.WapPushMessageRequest WapPushMessageRequest) {
            this.WapPushMessageRequest = WapPushMessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendWapPushResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altiria.net/api/soap", Order=0)]
        public PlannerWeb.SMS.WapPushMessageResponse WapPushMessageResponse;
        
        public sendWapPushResponse() {
        }
        
        public sendWapPushResponse(PlannerWeb.SMS.WapPushMessageResponse WapPushMessageResponse) {
            this.WapPushMessageResponse = WapPushMessageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.altiria.net/api/soap")]
    public partial class CreditRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Credentials credentialsField;
        
        /// <remarks/>
        public Credentials credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
                this.RaisePropertyChanged("credentials");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.altiria.net/api/soap")]
    public partial class CreditResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private decimal creditField;
        
        private bool creditFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("credit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creditSpecified {
            get {
                return this.creditFieldSpecified;
            }
            set {
                this.creditFieldSpecified = value;
                this.RaisePropertyChanged("creditSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altiria.net/api/soap", Order=0)]
        public PlannerWeb.SMS.CreditRequest CreditRequest;
        
        public getCreditRequest() {
        }
        
        public getCreditRequest(PlannerWeb.SMS.CreditRequest CreditRequest) {
            this.CreditRequest = CreditRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altiria.net/api/soap", Order=0)]
        public PlannerWeb.SMS.CreditResponse CreditResponse;
        
        public getCreditResponse() {
        }
        
        public getCreditResponse(PlannerWeb.SMS.CreditResponse CreditResponse) {
            this.CreditResponse = CreditResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsGatewayPortChannel : PlannerWeb.SMS.SmsGatewayPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsGatewayPortClient : System.ServiceModel.ClientBase<PlannerWeb.SMS.SmsGatewayPort>, PlannerWeb.SMS.SmsGatewayPort {
        
        public SmsGatewayPortClient() {
        }
        
        public SmsGatewayPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsGatewayPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsGatewayPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsGatewayPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PlannerWeb.SMS.sendSmsResponse PlannerWeb.SMS.SmsGatewayPort.sendSms(PlannerWeb.SMS.sendSmsRequest request) {
            return base.Channel.sendSms(request);
        }
        
        public PlannerWeb.SMS.TextMessageResponse sendSms(PlannerWeb.SMS.TextMessageRequest TextMessageRequest) {
            PlannerWeb.SMS.sendSmsRequest inValue = new PlannerWeb.SMS.sendSmsRequest();
            inValue.TextMessageRequest = TextMessageRequest;
            PlannerWeb.SMS.sendSmsResponse retVal = ((PlannerWeb.SMS.SmsGatewayPort)(this)).sendSms(inValue);
            return retVal.TextMessageResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PlannerWeb.SMS.sendWapPushResponse PlannerWeb.SMS.SmsGatewayPort.sendWapPush(PlannerWeb.SMS.sendWapPushRequest request) {
            return base.Channel.sendWapPush(request);
        }
        
        public PlannerWeb.SMS.WapPushMessageResponse sendWapPush(PlannerWeb.SMS.WapPushMessageRequest WapPushMessageRequest) {
            PlannerWeb.SMS.sendWapPushRequest inValue = new PlannerWeb.SMS.sendWapPushRequest();
            inValue.WapPushMessageRequest = WapPushMessageRequest;
            PlannerWeb.SMS.sendWapPushResponse retVal = ((PlannerWeb.SMS.SmsGatewayPort)(this)).sendWapPush(inValue);
            return retVal.WapPushMessageResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PlannerWeb.SMS.getCreditResponse PlannerWeb.SMS.SmsGatewayPort.getCredit(PlannerWeb.SMS.getCreditRequest request) {
            return base.Channel.getCredit(request);
        }
        
        public PlannerWeb.SMS.CreditResponse getCredit(PlannerWeb.SMS.CreditRequest CreditRequest) {
            PlannerWeb.SMS.getCreditRequest inValue = new PlannerWeb.SMS.getCreditRequest();
            inValue.CreditRequest = CreditRequest;
            PlannerWeb.SMS.getCreditResponse retVal = ((PlannerWeb.SMS.SmsGatewayPort)(this)).getCredit(inValue);
            return retVal.CreditResponse;
        }
    }
}
